spring.application.name=Ecomm

spring.datasource.url=jdbc:mysql://localhost:3306/ecommDB
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gmail SMTP Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={Admin_email}

spring.mail.password={Admin_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key.id={Key_id}
razorpay.key.secret={Key_secret}

